export const products = [
  {
    id: 1,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/boxy%20hoodie.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/boxy%20hoodie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/mens%20hoodie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/womens%20hoodie.jpg", 
    ],
    name: "Boxy Hoodie",
    description: "Warm and stylish hoodie.",
    price: 400,
    category: "Top",
    tag: "Bestseller",
    customisable: true,
    sizes: ["sm", "m", "l"],
    rating: 4.8,
    reviews: 72,
  },
  {
    id: 2,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/tshirt.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/tshirt.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/pocket%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/oversised%20tee.jpg",
    ],
    name: "Classic T-Shirt",
    description: "Soft cotton t-shirt.",
    price: 250,
    category: "Top",
    tag: "Classic",
    customisable: true,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 3,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/sweatshirt.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/sweatshirt.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/sweatshirt.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/long%20sleeve%20sweatshirt.jpg",
    ],
    name: "Crewneck Sweatshirt",
    description: "Cozy and casual.",
    price: 350,
    category: "Top",
    tag: "Popular",
    customisable: true,
    sizes: ["sm", "m", "l"],
    rating: 4.7,
    reviews: 65,
  },
  {
    id: 4,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/long%20sleeve.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/long%20sleeve.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/raglan%20long%20sleeve.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/v-neck%20long%20sleeve.jpg",
    ],
    name: "Long Sleeve Tee",
    description: "Warm long sleeve.",
    price: 300,
    category: "Outerwear",
    tag: "Winter Collection",
    customisable: true,
    sizes: ["m", "l", "xl"],
    rating: 4.9,
    reviews: 80,
  },
  {
    id: 5,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/bucket%20hat.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/bucket%20hat.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/roped%20bucket%20hat.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/orange%20bucket%20hat.jpg",
    ],
    name: "Bucket Hat",
    description: "Trendy bucket hat.",
    price: 150,
    category: "Accessory",
    tag: "Summer Essential",
    customisable: true,
    sizes: ["one size"],
    rating: 4.6,
    reviews: 40,
  },
  {
    id: 6,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/beanie.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/beanie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/winter%20beanie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/pom%20pom%20beanie.jpg",
    ],
    name: "Knitted Beanie",
    description: "Warm knitted beanie.",
    price: 200,
    category: "Accessory",
    tag: "Winter Essential",
    customisable: true,
    sizes: ["one size"],
    rating: 4.7,
    reviews: 35,
  },
  {
    id: 7,
    image: "",
    thumbnails: [],
    name: "Ski Mask",
    description: "Comfortable ski mask.",
    price: 250,
    category: "Accessory",
    customisable: true,
    sizes: ["one size"],
    rating: 4.5,
    reviews: 20,
  },
  {
    id: 8,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/polo%20shirt.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Customizable/polo%20shirt.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/oversized%20polo%20shirt.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/long%20sleeve%20polo%20shirt.jpg",
    ],
    name: "Polo Shirt",
    description: "Smart casual polo.",
    price: 300,
    category: "Top",
    tag: "Popular",
    customisable: true,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.6,
    reviews: 45,
  },
  {
    id: 9,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/sweatpants%201.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/sweatpants%201.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/sweatpants%202.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Thumbnails/sweatpants%203.jpg",
    ],
    name: "Cozy Sweatpants",
    description: "Comfortable and stylish top grade sweatpants.",
    price: 400,
    category: "Bottom",
    tag: "Classic",
    customisable: true,
    sizes: ["sm", "m", "l"],
    rating: 4.8,
    reviews: 72,
  },
  // ---- Anime Section ----
  {
    id: 10,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20hoodie.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20hoodie.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20hoodie.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20hoodie.jpeg",
    ],
    name: "One Piece Hoodie",
    description: "Straw Hat Pirates hoodie.",
    price: 480,
    category: "Top",
    tag: "Bestseller",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.9,
    reviews: 78,
  },
  {
    id: 11,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/naruto%20tee.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/naruto%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/naruto%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/naruto%20tee.jpeg",
    ],
    name: "Naruto Tee",
    description: "Naruto Uzumaki tee.",
    price: 320,
    category: "Top",
    tag: "Popular",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.7,
    reviews: 60,
  },
  {
    id: 12,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/demon%20slayer.png",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/demon%20slayer.png",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/demon%20slayer.png",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/demon%20slayer.png",
    ],
    name: "Demon Slayer Tee",
    description: "Demon Slayer Corps tee.",
    price: 320,
    category: "Top",
    tag: "Popular",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.7,
    reviews: 55,
  },
  {
    id: 13,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/gojo%20tee.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/gojo%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/gojo%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/gojo%20tee.jpeg",
    ],
    name: "Gojo Satoru Tee",
    description: "Gojo inspired tee.",
    price: 335,
    category: "Top",
    tag: "New",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.8,
    reviews: 72,
  },
  {
    id: 14,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itachi%20hoodie.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itachi%20hoodie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itachi%20hoodie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itachi%20hoodie.jpg",
    ],
    name: "Itachi Hoodie",
    description: "Itachi Uchiha hoodie.",
    price: 460,
    category: "Top",
    tag: "Classic",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.8,
    reviews: 65,
  },
  {
    id: 15,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itatchi%20tee.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itatchi%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itatchi%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/itatchi%20tee.jpg",
    ],
    name: "Itachi Tee",
    description: "Itachi Uchiha tee.",
    price: 330,
    category: "Top",
    tag: "Popular",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.8,
    reviews: 68,
  },
  {
    id: 16,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/japanese%20themed%20tee.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/japanese%20themed%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/japanese%20themed%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/japanese%20themed%20tee.jpeg",
    ],
    name: "Japanese Kanji Tee",
    description: "Minimal kanji graphic tee.",
    price: 310,
    category: "Top",
    tag: "New",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.6,
    reviews: 48,
  },
  {
    id: 17,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/madara%20tee.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/madara%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/madara%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/madara%20tee.jpg",
    ],
    name: "Madara Tee",
    description: "Madara Uchiha tee.",
    price: 350,
    category: "Top",
    tag: "Winter Essential  ",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.9,
    reviews: 90,
  },
  {
    id: 18,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20custom%20tee%202.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20custom%20tee%202.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20custom%20tee%202.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20custom%20tee%202.jpg",
    ],
    name: "Custom Anime Tee",
    description: "Unique anime design tee.",
    price: 300,
    category: "Top",
    tag: "Classic",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.7,
    reviews: 70,
  },
  {
    id: 19,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/Aot%20hoodie.webp",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/Aot%20hoodie.webp",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/Aot%20hoodie.webp",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/Aot%20hoodie.webp",
    ],
    name: "Attack on Titan Hoodie",
    description: "Scout Regiment inspired hoodie.",
    price: 450,
    category: "Top",
    tag: "Winter Collection",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.9,
    reviews: 85,
  },
  {
    id: 20,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20tee.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20tee.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/op%20tee.jpeg",
    ],
    name: "One Piece Tee",
    description: "One Piece crew tee.",
    price: 325,
    category: "Top",
    tag: "Popular",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.7,
    reviews: 58,
  },
  {
    id: 21,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/rick%20tee.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/rick%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/rick%20tee.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/rick%20tee.jpg",
    ],
    name: "Rick & Morty Tee",
    description: "Cartoon inspired tee.",
    price: 300,
    category: "Top",
    tag: "Summer Essential",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.6,
    reviews: 50,
  },
  {
    id: 22,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20hoodie.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20hoodie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20hoodie.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20hoodie.jpg",
    ],
    name: "Solo Leveling Hoodie",
    description: "Sung Jin-Woo hoodie.",
    price: 470,
    category: "Top",
    tag: "New",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.8,
    reviews: 67,
  },
  {
    id: 23,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%201.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%201.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%201.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%201.jpg",
    ],
    name: "Solo Leveling Tee",
    description: "Shadow Monarch tee.",
    price: 330,
    category: "Top",
    tag: "Bestseller",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.7,
    reviews: 55,
  },
  {
    id: 24,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%202.jpg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%202.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%202.jpg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/solo%20tee%202.jpg",
    ],
    name: "Solo Leveling Tee 2",
    description: "Alt Solo Leveling tee.",
    price: 340,
    category: "Top",
    tag: "Classic",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.8,
    reviews: 64,
  },
  {
    id: 25,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20thing%20hoodie.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20thing%20hoodie.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20thing%20hoodie.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/anime%20thing%20hoodie.jpeg",
    ],
    name: "Anime Thing Hoodie",
    description: "Bold anime hoodie.",
    price: 470,
    category: "Hoodie",
    tag: "Winter Collection",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.8,
    reviews: 67,
  },
  {
    id: 26,
    image:
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/dbz%20hoodie.jpeg",
    thumbnails: [
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/dbz%20hoodie.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/dbz%20hoodie.jpeg",
      "https://ovyqedcljkayiue8.public.blob.vercel-storage.com/Anime%20Selection/dbz%20hoodie.jpeg",
    ],
    name: "Dragon Ball Z Hoodie",
    description: "Goku Super Saiyan hoodie.",
    price: 320,
    category: "Hoodie",
    tag: "New",
    customisable: false,
    sizes: ["sm", "m", "l", "xl"],
    rating: 4.7,
    reviews: 60,
  },
];
